# Generated by Django 5.0 on 2023-12-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ties',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
