# Generated by Django 4.2.8 on 2023-12-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0002_game_player_1_moves_game_player_2_moves'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='code',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
