# Generated by Django 4.2.8 on 2023-12-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0003_game_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player_2_id',
            field=models.IntegerField(null=True),
        ),
    ]
