# Generated by Django 4.2.8 on 2023-12-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0004_alter_game_player_2_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player_1_moves',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_2_moves',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
