# Generated by Django 4.2.8 on 2023-12-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0008_alter_game_player_1_moves_alter_game_player_2_moves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player_1_moves',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_2_moves',
            field=models.CharField(default='', max_length=255),
        ),
    ]
