# Generated by Django 4.2.8 on 2023-12-18 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0011_game_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='invitation',
        ),
    ]
