# Generated by Django 4.2.8 on 2023-12-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0012_delete_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner_id',
            field=models.IntegerField(null=True),
        ),
    ]
